export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const RESET_PRODUCT_CART = 'RESET_PRODUCT_CART';
export const COUNT_TOTAL_PRICE = 'COUNT_TOTAL_PRICE';
//export const GET_ERRORS = 'GET_ERRORS';